baseURL: "https://jisoohur.github.io/portfolio/" 
title: Dr. Jisoo Hur
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Jisoo Hur's research papers, curriculum vitae, and contact information."
    author: Jisoo Hur
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr Jisoo Hur
          subtitle: "I am a postdoctoral researcher at the TUM School of Management, Technical University of Munich, Germany. My research focuses on inventor mobility and collaboration, regional knowledge spillovers, and the semantic proximity between scientific and technological knowledge. Using large-scale patent data, I apply advanced analytical methods—including topic modeling, large language models (LLMs), and other computational techniques—to investigate how knowledge flows and evolves across regions, technologies, and inventor networks."
          imageUrl: "profile picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: jisoo.hur@tum.de
        - name: Zoom
          url: https://us04web.zoom.us/j/5969198999?pwd=0h373MdazdueeJicfubrLwnuq6Mvhu.1
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=IUY_S1QAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/Jisoohur
        - name: LinkedIn
          url: https://www.linkedin.com/in/jisoo-hur-10a07a24a/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jisoo Hur"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
